### ISSUE TITLE
Add Products

### ISSUE THREAD

**Issue by adrianskelton** [adrianskelton/adrianproject5#8]
Add all products and categories for the shop

**Tasks:**

- [x] Import all products using loaddata from JSON products file
- [x] Create categories from JSON categories file
- [x] Create appropriate admin tables for product and categories
- [x] Replace imported data with original project specific data
